branches:
  only:
  - master
  - dev
sudo: enabled
language: bash
script: 
    - bash which-branch.sh
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - nmagee@gmail.com
