branches:
  only:
  - master
  - staging
  - dev

# sudo: enabled

language: bash

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - bash -c 'which aws'
  - bash -c 'whereis aws'

install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --no-cache -t somrc/lolatest:latest . ;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push somrc/lolatest:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then
    docker build --no-cache -t somrc/lolatest:staging . ;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push somrc/lolatest:staging;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then
    cd dev/ ;
    docker build --no-cache -t somrc/lolatest:dev . ;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push somrc/lolatest:dev;
    aws sqs send-message --region=us-east-1 --queue-url 'https://queue.amazonaws.com/474683445819/lola-updates' --message-body '$TRAVIS_BRANCH';
    fi

# script:
#   - /home/travis/.local/bin/aws sqs list-queues

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_PASSWORD";
#     docker push USER/REPO;
#     fi
#   # Create a message in SQS
#   - provider: script
#     script: ./home/travis/.local/bin/aws sqs send-message --queue-url 'https://queue.amazonaws.com/474683445819/lola-updates' --message-body '$TRAVIS_BRANCH'

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nmagee@gmail.com

